export const GET_BUILDING = 'GET_BUILDING'
export const GET_BUILDING_HPD_VIOLATIONS = 'GET_BUILDING_HPD_VIOLATIONS'
export const HANDLE_GET_BUILDING = 'HANDLE_GET_BUILDING'
export const HANDLE_GET_BUILDING_HPD_VIOLATIONS = 'HANDLE_GET_BUILDING_HPD_VIOLATIONS'
