export const SET_DASHBOARD_MAP_ZOOM = 'SET_DASHBOARD_MAP_ZOOM'
export const LOAD_RESULT_FILTERS = 'LOAD_RESULT_FILTERS'
export const SET_HOUSING_TYPE_RESULT_FILTER = 'SET_HOUSING_TYPE_RESULT_FILTER'
export const SET_MAP_FILTER_DATE = 'SET_MAP_FILTER_DATE'
