export const SEARCH_URL = '/search/buildings/'
export const TOKEN_URL = '/api/token/'
export const TOKEN_REFRESH_URL = '/api/token/refresh/'
export const CURRENT_USER_URL = '/users/current/'
export const BUILDING_URL = '/buildings/'
export const HPD_VIOLATIONS_URL = '/hpdviolations/'
export const DOB_VIOLATIONS_URL = '/dobviolations/'
export const HPD_COMPLAINTS_URL = '/hpdcomplaints/'
