export const SET_BOUNDARY_TYPE = 'SET_BOUNDARY_TYPE'
export const SET_BOUNDARY_ID = 'SET_BOUNDARY_ID'
export const SET_BOUNDARY_TYPE_AND_ID = 'SET_BOUNDARY_TYPE_AND_ID'

export const UPDATE_BOUNDARY_FILTER = 'UPDATE_BOUNDARY_FILTER'
