export const BOOKMARK_PROPERTY = "BOOKMARK_PROPERTY";
export const UNBOOKMARK_PROPERTY = "UNBOOKMARK_PROPERTY";
export const GET_USER_BOOKMARKED_PROPERTIES = "GET_USER_BOOKMARKED_PROPERTIES";
export const CLEAR_USER_BOOKMARKED_PROPERTIES = "CLEAR_USER_BOOKMARKED_PROPERTIES";